influxdata/telegraf-operator

go.mod, sidecar_test.go
I wanted to understand the possible options to give telegraf, so, I wrote tests.
I also wanted to see the rendered Pod YAML.
=> Add basic tests for sidecar to demo output YAML

examples/classes.yml
While working with `telegraf-operator`, I have noticed that the default `classes.yml` does not make it easy to troubleshoot.
What I've done is made `basic`, `app` and `infra` log to influxDB 1.x as well as to stdout and renamed the examples that are using InfluxDB 2.0 as we do not have a ready to run example for InfluxDB 2.0.
I also found that logging data to stdout makes it easier to get started as I can see the outputs immediately.
=> fix: add useful and more practical classes to examples/classes.yml

go.mod, handler.go, handler_test.go, main.go
Closes #12
This changes how handling errors related to retrieving secret classes is handled to only log the error and not create sidecar instead of returning and error, as this prevents the pods to from being created at all.
=> fix: change logic for missing classes secret to log error instead of not creating pods

go.mod, go.sum, handler.go, handler_test.go, sidecar.go, sidecar_test.go
Closes #13 
This change splits `assembleConf` logic from `addSidecar`. In case of errors in `assembleConf`, fail silently and log an error.
Added unit tests as well as manually validated valid and invalid TOML files are working as expected.
=> feat: add validation that Telegraf config is has valid TOML syntax

README.md, handler.go, handler_test.go, main.go, sidecar.go, sidecar_test.go
Closes #11
Allows passing telegraf image as command line option as well as using an annotation.
=> feat: add support for customizing telegraf image

deploy/dev.yml, handler.go, handler_test.go, main.go, sidecar.go, sidecar_test.go
Closes #10
Adds option and passes it to sidecar generation logic.
I've also made the `sidecarConfig` type to simplify adding more configuration specific to sidecar containers.
=> feat: add --enable-default-internal-plugin to enable inputs.internal globally

README.md, deploy/dev.yml, deploy/influxdb.yml, examples/classes.yml
Closes #21
Improve README file with more detailed instructions for setting up `telegraf-operator`.
This also adds Chronograf to the InfluxDB deployment to simplify visualisation of the data.
=> chore: improve README file with more detailed usage instructions

Dockerfile, class_data.go, class_data_test.go, deploy/dev.yml, handler.go, handler_test.go, main.go
* refactor: switch to using directory for reading classes instead of secret
* feat: add validation that all classes are valid TOML files at startup
Closes #19
Closes #20 
Separates class data logic and refactor to read from directory instead of secret. Update `dev.yml` to reflect the changes.
Add validation at startup that checks at least one class exists and that all classes are valid TOML files.
=> refactor: switch to using directory for reading classes instead of secret

Dockerfile, README.md, examples/redis.yml, handler_test.go, main.go, sidecar.go, sidecar_test.go
Closes #27
Add configuration options along with validation for default resource requests and limits as well as an option to override those at individual pod level.
=> feat: allow configuring custom resources for telegraf sidecar

class_data.go
Related to #30
Check the link target (as opposed to the just symlink) to check whether it is a file or not.
=> fix: only read regular files, ignoring symlinks

sidecar_test.go
Closes #39
Update tests to use port 8086 instead of 9999.
=> chore: replace port 9999 with 8086 in tests

handler.go, handler_test.go, main.go, sidecar.go, sidecar_test.go
Closes #40 
Improves support for handling secrets for telegraf sidecar.
Adds checks to avoid accidental overwrite of secrets.
Adds an annotation to allow easier detection of secrets managed by `telegraf-operator` and flag to optionally only overwrite secrets with said annotation.
=> feat: improve secret management to handle existing secrets ; add annotation

README.md
Fix the urls within the readme for kubectl apply
Closes #
=> fix(readme): update direct apply urls

.circleci/config.yml
Upgrading the CircleCI go version used
=> fix(circleci): update circleci go version

.circleci/config.yml
Revert changes to CircleCI configuration that prevent creating a new release.
=> fix: revert changes to build-and-deploy job in CircleCI

sidecar.go, sidecar_test.go
Adds a label that specifies class that was used when creating and/or updating secrets required for pods.
This will make it easier to secrets managed by telegraf-operator and update them.
=> feat: add telegraf.influxdata.com/class label to secrets managed by telegraf

sidecar.go, sidecar_test.go
After investigating more about secret re-creation I realized that it may be easier to set the label on the secret rather than guess the pod name from the secret name.
=> chore: add pod-name label to all secrets to simplify updates of secrets

handler_test.go, main.go, sidecar.go, sidecar_test.go
Allows `telegraf` to be reloading configuration on changes so that at some point the secret for each pod can be regenerated.
Depends on influxdata/telegraf#9485 being merged and released for the `--telegraf-watch-config` option to be useful.
=> feat: allow passing --watch-config flag to telegraf

deploy/dev.yml, handler_test.go, main.go, sidecar_test.go
Enables telegraf hot reload in dev mode.
Also changes default image to latest 1.19 as it's needed for hot reloading to work.
=> chore: enable hot-reload in dev.yml ; update default version of telegraf to allow it

.circleci/config.yml
=> fix: add latest tag when releasing a new version of telegraf-operator

Makefile
Small change as the previous sleep was arbitrary and a wait based approach is more reliable.
=> chore(Makefile): improve waiting for telegraf-operator be ready in kind-test

sidecar.go, sidecar_test.go
Implements main form of the #82 proposal.
The implementation is quite quick&dirty; there are a few yaks to shave in order to make this more clean; in particular we should avoid fiddling with TOML as a string, but we should parse it and manipulate the AST or some intermediate representation. Unfortunately the TOML library we're using doesn't support marshaling back the AST back.
=> feat: Add telegraf.influxdata.com/global-tag-literal-

main.go
Decouples where TLS certificates are stored so `telegraf-operator` can be added to more places.
=> chore: allow setting certificate directory for webhook

sidecar.go, sidecar_test.go
Closes #84
Allows disabling resource requests and/or limits for telegraf sidecars by providing an empty string as value.
=> feat: allow disabling telegraf resources by providing an empty string

README.md, sidecar.go, sidecar_test.go
Closes #88 
This PR adds the following annotation: `telegraf.influxdata.com/metric-version`
When this annotation is present on a resource, the generated Prometheus input config will include the `metric_version` key:
```
[[inputs.prometheus]]
urls = ["http://127.0.0.1:6060/metrics"]
metric_version = 2
```
While there are only 2 possible values (1, 2), there was no validation present on other annotation values, so I did not include that here either. The blank line comes from not specifying the interval annotation. While it doesn't look the best, it is valid toml. If desired, I can refactor to remove the empty line.
=> Add capability to specify Prometheus metrics version

go.mod, go.sum
To address CVE-2021-3121:
$ go mod edit -require github.com/gogo/protobuf@v1.3.2
$ go mod tidy
=> chore: require 1.3.2 for indirect gogo/protobuf

_templates/community-operator/release/manifests-clusterserviceversion.ejs.t
Add permissions that are required if telegraf-operator is running with hot reloads of configuration enabled.
Currently it's not so it is not an issue but adding it for future release so it continues to work if someone enables hot reloads of configuration.
=> chore: update permissions in community-operators template

handler_test.go, main.go, sidecar_test.go
=> Bump Telegraf image to 1.22

README.md
Updates README.md to reflect current ways to install `telegraf-operator`, also making the non-development getting started easier.
=> chore: update README.md and add links

README.md, examples/deployment.yml, sidecar.go, sidecar_test.go
Allow providing `namepass` annotation to limit metrics that are gathered via Prometheus scraping.
Also update example deployment to have an image that provides metrics and provide `namepass` in the example.
=> feat: add namepass for metric scraping; cleanup config generation

scripts/release/update-community-operators.bash
Automates the signoff of commit for community-operators, which caused PRs to fail CI in the past
=> chore(scripts): commit with --signoff for community-operators release

README.md, sidecar.go
Closes #103
**add new Annotation**: **"telegraf.influxdata.com/volume-mounts"**
the above TelegrafVolumeMounts Annotation allows specifying custom extra volumes to mount on telegraf sidecar, should be json formatted, eg: {"volumeName": "mountPath"}
`telegraf.influxdata.com/volume-mounts: {"xxx-3080bfa7-log":"/opt/xxx/log"}`
also, it can support multi-volume mount, eg:
```
telegraf.influxdata.com/volume-mounts: {"xxx-3080bfa7-log":"/opt/xxx/log","xxx-3080bfa7-conf":"/opt/xxx/conf"}
```
**Prerequisites**：
**the extra-volume must already existed in the pod,**
the volume-mounts annotation just told telegraf-operator to mount the exist volume into telegraf sidecar container's some direction.
I have tested in our environment.
([if …
=> feat: support extra volume mounts, incloude support multi-volume mount

go.mod, go.sum, sidecar.go
Fixes local:
```bash
$ make test    
/Users/mkm/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
go fmt ./...
sidecar.go
go vet ./...
../../go/pkg/mod/github.com/kudobuilder/kuttl@v0.12.1/pkg/test/utils/docker.go:14:44: undefined: volumetypes.VolumeCreateBody
../../go/pkg/mod/github.com/kudobuilder/kuttl@v0.12.1/pkg/test/utils/docker.go:14:75: undefined: dockertypes.Volume
make: *** [vet] Error 1
```
=> fix: Revert bump of github.com/docker/docker

main.go
This PR adds the `--zap-*` flags. This is commonly used in the ecosystem, see https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/
=> feat: Expose zap logger flags
